### PR TITLE
use getfullargspec when possible

### PR DESCRIPTION
**Pull request by kindermax**

### CODE REVIEW

**Comment by vmagamedov** [comment]
Can you elaborate on what you're fixing by using `getfullargspec`? It would be great to also add a corresponding test.

**Comment by vmagamedov** [comment]
Aha, I see, `inspect.getargspec()` is deprecated. Please fix Python 3.4 support and I'm ok to merge your PR.

**Comment by kindermax** [comment]
Yes, I'm pushed to see how tests will go. I will fix it soon. Thanks)

**Comment by vmagamedov** [comment]
It is worth to mention that this PR actually fixes the case when "defined" function contains annotations:
```python
...
  File "/usr/local/lib/python3.8/dist-packages/sqlconstruct.py", line 772, in define
    spec = inspect.getargspec(func)
  File "/usr/lib/python3.8/inspect.py", line 1083, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
```

**Pull request merged**
